"""Database access layer — phase 1. All access via get_connection()."""

from .bioreactors import (
    BioreactorDefinition,
    bioreactor_parameters,
    bioreactor_usage,
    delete_bioreactor,
    export_bioreactor,
    free_bioreactor_name,
    import_bioreactor,
    list_bioreactors,
    load_bioreactor,
    write_bioreactor,
)
from .connection import get_connection
from .maintenance import database_size, vacuum_database
from .migrate import apply_migration, ensure_columns, ensure_indexes
from .models import (
    Condition,
    Lookups,
    Phase,
    ProjectInfo,
    ProjectSetup,
    VariableSeries,
)
from .project import (
    DeletionCancelledError,
    create_model,
    create_project,
    delete_model,
    delete_project,
    duplicate_model,
    free_model_name,
    list_models,
    list_projects,
    load_model_defaults,
    load_phases,
    load_project_info,
    load_project_log,
    load_project_variables,
    model_parameters,
    model_usage,
    save_model_parameters,
    save_project,
    save_project_with_backup,
    unique_project_name,
    update_model,
)
from .seed import export_defaults, load_defaults, refresh_reference_values
from .transfer import (
    MANIFEST,
    MissingPrerequisiteError,
    ProjectPackage,
    check_prerequisites,
    import_package,
    read_package,
    write_manifest,
)

__all__ = [
    "MANIFEST",
    "BioreactorDefinition",
    "Condition",
    "DeletionCancelledError",
    "Lookups",
    "MissingPrerequisiteError",
    "Phase",
    "ProjectInfo",
    "ProjectPackage",
    "ProjectSetup",
    "VariableSeries",
    "apply_migration",
    "bioreactor_parameters",
    "bioreactor_usage",
    "check_prerequisites",
    "create_model",
    "create_project",
    "database_size",
    "delete_bioreactor",
    "delete_model",
    "delete_project",
    "duplicate_model",
    "ensure_columns",
    "ensure_indexes",
    "export_bioreactor",
    "export_defaults",
    "free_bioreactor_name",
    "free_model_name",
    "get_connection",
    "import_bioreactor",
    "import_package",
    "list_bioreactors",
    "list_models",
    "list_projects",
    "load_bioreactor",
    "load_defaults",
    "load_model_defaults",
    "load_phases",
    "load_project_info",
    "load_project_log",
    "load_project_variables",
    "model_parameters",
    "model_usage",
    "read_package",
    "refresh_reference_values",
    "save_model_parameters",
    "save_project",
    "save_project_with_backup",
    "unique_project_name",
    "update_model",
    "vacuum_database",
    "write_bioreactor",
    "write_manifest",
]
